### PR TITLE
Added PDF and CSV support.

### PR DESCRIPTION
**Pull request by alxspiker**

### CODE REVIEW

**Comment by alxspiker** [comment]
Second commit because
```
if file.endswith(".txt"):
                loader = TextLoader(os.path.join(root, file), encoding="utf8")
            elif file.endswith(".pdf"):
                loader = PDFMinerLoader(os.path.join(root, file))
            elif file.endswith(".csv"):
                loader = CSVLoader(os.path.join(root, file))
```
didnt commit.

**Comment by su77ungr** [comment]
perfect. lgtm. thanks

**Comment by su77ungr** [comment]
reminder: keep requirements.txt up to date if PDFMinerLoader, CSVLoader need extra dependencies

**Comment by alxspiker** [comment]
> reminder: keep requirements.txt up to date if PDFMinerLoader, CSVLoader need extra dependencies

I thought they came from langchain.

**Pull request merged**
