### PR TITLE
GUI SUPPORT

### PR DESCRIPTION
**Pull request by alxspiker**
First working edition!
Ill continue adding to this PR to make it more complete.
Commit if you want right away, I tested and ran multiple queries.

I want to see if I can get an ingest page to ingest using the GUI too.

Run `streamlit run .\gui.py` to use it.

image

### CODE REVIEW

**Comment by alxspiker** [comment]
I know, I am awesome :P

**Comment by su77ungr** [comment]
Your development speed is incredible. Give me a break already 🥇 

I like the approach without spawning a server.

**Comment by alxspiker** [comment]
Its looking great, just diving right in.

**Comment by su77ungr** [comment]
You could use the dev branch for your GUI implementation + feel free to bootsrap it into another Dockerfile

**Comment by alxspiker** [comment]
I don't know much about docker, so I dont understand the failing check.

**Comment by su77ungr** [comment]
Don't worry just ignore it for now. I can't use workflows outside the main branch right now.

**Comment by su77ungr** [comment]
also push a test. should be working now

**Comment by su77ungr** [comment]
Don't worry about it. Dockerfile should be fixed soon. Just ignore it for now

**Comment by alxspiker** [comment]
Works as intended now for chatting with the documents AI. Also learned a lot about steamlit.
P.S. Still needs code cleanup, working on that right now.

**Comment by alxspiker** [comment]
Getting an error on second query:
```
RuntimeError: Storage folder db is already accessed by another instance of Qdrant client. If you require concurrent access, use Qdrant server instead.
```

**Comment by su77ungr** [comment]
when running main or inside your implementation?

**Comment by alxspiker** [comment]
Testing both to make sure, got a fix for the GUI, just got to test it.

**Comment by alxspiker** [comment]
Ah, got a small fix coming for startLLM. Seems like I was caching the DB and LLM when I didnt need to, also gui check for user input was incorrect.

**Comment by alxspiker** [comment]
And done!
image

**Comment by alxspiker** [comment]
Tested both console and gui, works as intended.

**Comment by alxspiker** [comment]
Adding controls now to change .env on the fly
image

**Comment by alxspiker** [comment]
image

**Comment by alxspiker** [comment]
All done for now, edit it as you wish, ill work on the ingest page tonight or tomorrow.

**Comment by alxspiker** [comment]
I still randomly get RuntimeError: Storage folder db is already accessed by another instance of Qdrant client. If you require concurrent access, use Qdrant server instead.

It seems lik 1/5 runs

**Comment by su77ungr** [comment]
Perfect. Thanks for the awesome workflow. 

I'm setting up a dependencies check and docker workflow so we can prototype without any issues. 

Noticed some similiar behaviour, so might switch out both models and run with default arguments. Also I'd like to take a look at the LlamaCpp compiler

**Comment by imSrbh** [comment]
ModuleNotFoundError: No module named 'streamlit.proto.BackMsg_pb2'
looks like streamlit version issue

**Pull request merged**
